# Generated by Django 4.0.6 on 2022-08-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=20, verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('TODO', 'To do'), ('IN_PROGRESS', 'In progress'), ('DONE', 'Done')], max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tag',
            field=models.CharField(choices=[('BUG', 'Bug'), ('ENHANCEMENT', 'Enhancement'), ('TASK', 'Task')], max_length=20, verbose_name='tag'),
        ),
    ]
